
    version: '3'
    services:
      bot:
        build: .
        ports:
          - "3000:3000"
        environment:
          - TELEGRAM_TOKEN=your_telegram_token
          - DATABASE_URL=your_database_url
        volumes:
          - .:/app
        command: ["node", "index.js"]
    